ourschool/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django_extensions.db.fields import AutoSlugField
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class source(models.Model):
  #source of learning - to populate available classes. flexible enough for many formats
  
  #Possible class statuses
  STATUS_CHOICES = (
                    ('active','Active Now'),
                    ('proposed','Proposed'),
                    ('finished','Finished'),
                    ('canceled','Canceled'),
                    ('starting','Starting Soon'),
                    
                    
                    )
  
  #Possible class formats
  FORMAT_CHOICES = (
                    ('colearn','Co-Learn'),
                    ('handson','Hands-On'),
                    ('seminar','Seminar'),
                    ('lecture','Lecture'),
                    ('discussion','Discussion'),
                    ('bookclub','Book Club'),
                    ('project','Project'),
                    ('dit','Do It Together'),
                    ('conversation','Conversation'),
                    ('story','Storytelling'),
                    ('collaboration','Collaboration'),
                    ('apprenticeship','Apprenticeship'),
                    ('mentoring','Mentoring'),
                    ('demonstration','Demonstration'),
                    ('skillshare','Skillshare / Skilltrade'),
                    ('freeform','Freeform'),
                    ('competition','Competition'),
                    ('game','Game Learning'),
                    ('localmedia','Local Media'),
                    ('volunteering','Volunteering'),
                    ('other','Other'),
                    ('intensive','Intensive'),                    
                    )
  

  classtitle = models.CharField(max_length='70',verbose_name='Title',unique=True,help_text='example: Learn Permacultural Approaches To Oral Hygeine / Bicycles!')
  #title of class
  #classslug = AutoSlugField(max_length=50, unique=True, populate_from=('classtitle',))
  #class slug
  classdescription = models.TextField(verbose_name='Description',help_text='Write about your relevant experience (if any!), learning goals for yourself and others.  Also include prerequisites, materials costs, and anything else unique.')
  #description of class
  classstatus = models.CharField(max_length='30',blank=True,verbose_name='Status',choices=STATUS_CHOICES)
  #does the class exist, is it finished, or is it only proposed?
  classsubject = models.CharField(max_length='30',blank=True,verbose_name='Subject',help_text='Broad subject, i.e.: Philosophy')
  #broad subject, i.e. programming
  classformat = models.CharField(max_length='40',blank=True,verbose_name='Format',choices=FORMAT_CHOICES,help_text='See help for format explanations')
  #format of class, i.e. lecture
  classhost = models.CharField(max_length='50',blank=True,verbose_name='Host',help_text='Teacher, Facilitator, Organization, or Host of class')
  #who teaches or initiates it, i.e. community member, communecos, etc  
  classstartdate = models.DateField(blank=True,verbose_name='Start Date',help_text='First Learning Date')
  #start date
  classnextdate = models.DateField(blank=True,verbose_name='Next Date',help_text='Next Date of Activity')
  #next date
  classfrequency = models.CharField(max_length='40',verbose_name='Frequency',help_text='i.e. Weekly, One Time, Daily, etc.')
  classcost = models.CharField(max_length='40',blank=True,verbose_name='Cost?',default='Free',help_text='Most should be free.  Others accept money, IOUs, barter, work trade, food, etc.!')
  #free, ious, villages, $30, etc.
  classaccredited = models.BooleanField(blank=True,verbose_name='Accredited?',help_text='Whether or not you (informally) offer recognition of work done by others in this context, even if they are your peers.')
  #is some kind of credit given?
  classsite = models.URLField(blank=True,verbose_name='Info Website',help_text='Website with info about the class')
  #url for more info
  classgroupurl = models.URLField(blank=True,verbose_name='Resource Website',help_text='Website for a class google group, wiki, etc.')
  #url for a google group, wiki, etc.
  classemail = models.EmailField(blank=True,verbose_name='Host Email',help_text='Contact Email For the Learning')
  #email of instructor or organization
  classusers = models.ManyToManyField('UserProfile',related_name='participants',blank=True)
  #users participating in a class
  classinterested = models.ManyToManyField('UserProfile',related_name='interested',blank=True)
  #users interested in a class
  classcertified = models.ManyToManyField('UserProfile',related_name='certified',blank=True)
  #users certified in a class
  classteachers = models.ManyToManyField('UserProfile',related_name='teachers',blank=True)
  #teacher of class user model
  classcreator = models.ForeignKey(User,unique=True)
  #created the class
  classtown = models.CharField(max_length='40',verbose_name='City',blank=True)
  classlocation = models.TextField(blank=True,verbose_name='Instructions For Joining This Learning',help_text='How does someone sign up for this Learning, or express interest in starting one with you? Give contact info here, which can include a website for your organization, an e-mail address, or a time and place where you\'ll be gathering to learn.')
  #where the class is taking place
  classphoto = models.ImageField(blank=True,verbose_name='Image',upload_to='media/classphotos/')
  #image for class
  classrelated = models.ManyToManyField('self',blank=True,verbose_name='Related Classes')
  #related classes
  classurl = AutoSlugField(populate_from='classtitle')
  
  
  def _get_password(self):
    password = User.objects.make_random_password()
    return password
    
  #password to edit class
  classpass = _get_password
  
  def _get_fields(self):
    return [(field.name, field.value_to_string(self)) for field in source._meta.fields]
  
  #def _get_url(self):
    #makes URL from class title
  #  return slugify(self.classtitle)
  
  #classurl = property(_get_url)
  
  def _get_num_users(self):
    #Gets number of users
    return len(self.classusers)
  
  classnumusers = property(_get_num_users)
  
  def _get_is_free(self):
    #Checks if class is free
    if self.classcost == 'Free' or self.classcost == 'free':
      return 'Yes'
    else:
      return 'No'
  
  classisfree = property(_get_is_free)
  

  
  
  def __unicode__(self):
    return self.classtitle

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

class UserProfile(models.Model):  
    user = models.ForeignKey(User,unique=True)  
    #other fields here
    about = models.TextField(blank=True,verbose_name='Something About You',help_text='Who are you?')
    user_photo = models.ImageField(blank=True,verbose_name='Your Photo',upload_to='media/participantphoto/')
    classes_taken = models.ManyToManyField('source',related_name='attended',blank=True)
    classes_taught = models.ManyToManyField('source',related_name='taught',blank=True)
    classes_certified = models.ManyToManyField('source',related_name='certified',blank=True)
    classes_interested = models.ManyToManyField('source',related_name='interested',blank=True)
    hours_given = models.IntegerField(default=0,blank=True)
    website = models.URLField(blank=True,verbose_name='Your Website')
    selfcred_page = models.URLField(blank=True,verbose_name='Your Accreditation',help_text='Do you document your learning online?  Put the URL here!')
    interestedin = models.TextField(blank=True,verbose_name='Interested In Learning',help_text='What are you interested in learning?')
    
    def __str__(self):  
          return "%s's profile" % self.user  
 
def create_user_profile(sender, instance, created, **kwargs):  
    if created:  
       profile, created = UserProfile.objects.get_or_create(user=instance)  
 
post_save.connect(create_user_profile, sender=User)
 
User.profile = property(lambda u: u.get_profile() )

learningcommons/templates/home.html
{% extends 'base.html' %}

{% block title %}Piedmont Learning Commons | A Free Community Approach To Class{% endblock %}

{% block content %}
<div id="content">
<div class="grid">
	<div class="col-2-3">
		 <div id="intro-text">
				<strong>Learning is everywhere. Discover debt-free sources of learning in our community.</strong>
				</div>
		<div class="rounded-box">
			<h2>Find a Local Learning Opportunity</h2>
			<strong>
			<div class="class-listing">
				<div class="class-nextdate">
					Date
				</div>
				<div class="class-name">
					Learning
				</div>
				<div class="class-format">
					Format
				</div>
				
				<div class="class-isfree">
					Free?
				</div>
				
			</div>
			</strong> 
			<br>
			
			{% for class in classes %}
			<div class="class-listing">
				<div class="class-nextdate">
					{{ class.classnextdate|date:"M d" }}
				</div>
				<div class="class-name">
					<a href='viewlearning/{{ class.classurl }}'>{{ class }}</a>
				</div>
				<div class="class-format">
					{{ class.get_classformat_display }}
				</div>
				
				<div class="class-isfree">
					{{ class.classisfree }}
				</div>
				
			</div>
			<br/>
			{% endfor %}
			<div id="search-and-see-all">
				<div id="search-area">
					<strong>Search for a class:</strong>
					<br/>
					{% if errors %}
					{% for error in errors %}
					<br/>
					{{ error }}
					{% endfor %}
					<br/>
					{% endif %}
					{% include 'includes/search.html' %}
				</div>
				<div id="see-all"><br/>
					<a href='/view-all/'>See all classes</a>.
				</div>
			</div>
		</div>
		<div id="teach-area" class="rounded-box">
			<h2>Teach or Learn Together</h2>
			<p>Have a skill or subject you’d love to share with your community? 
			</b><br><a href="submitlearning/">Add your local Learning</a>
			</p>
	        <p>Not sure what to teach?<br>  How about a seminar on <strong>{{ suggestion }}</strong>.</p>
		</div>
		<div id="about" class="clear-box col-2-3">
			<h2>What is a Learning Commons?</h2>
			<p>
				Dozens of workshops are taught in your community each year.  Book clubs and discussion groups; crafters and gardeners; the retired professor who you always see at the grocery store.  Online, a simple search can turn up free online courses, video tutorials and DIY blog posts, open journal articles.  Learning is in abundance.
			</p>
			<p>
				A commitment to lifelong learning shouldn't have to mean a trap door to debt.  In the US, student loan debt is now greater than credit card debt, even as jobs disappear and transform rapidly enough to render too many degrees obselete.
			</p>
		</div>
		<div id="likely-never-see" class="rounded-box col-1-3">
			<h3>In a Learning Commons...</h3>
			<div id="likely-see">
				<strong>...you'll often see:</strong>
				<br/>
				<em>{{ likely }}</em>
				<br/>
				<br/>
			</div>
			<div id="never-see">
				<strong>...you'll never see:</strong>
				<br/>
				<em>{{ never }}</em>
				<br/>
				<br/>
				(see all)
				<br/>
			</div>
		</div>
	</div>
	<div class="col-1-3">
		<div id="sidebar">
		<div id="partners" class="rounded-box">
			<strong>Partners</strong>
			<br/>
			Carrboro Greenspace
			<br/>
			Splatspace
			<br/>
			Communecos
			<br/>
			The Abundance Foundation
			<br/>
			Seeds NC
			<br/>
		</div>

		<div id="nav" class="rounded-box">
			<strong>The Saloon - A local Pub</strong>
			<br/>
			An Open Academic Community Journal
			<br/>
			<br/>
			<strong>Who, Why, Wut?</strong>
			<br/>
			Who runs this conspiracy?
			<br/>
			<br/>
			<strong>Taking Back the Commons</strong>
			<br/>
			Not everything needs a price.</br>
			<br/>
			<strong>The LC Bloggy Blog</strong>
			<br/>
			Stories of debt, discovery, and getting schooled.
			<br/>
		</div>
		
		<div id="learning-icons" class="rounded-box">
			<strong>Find Learnings For:</strong><br/>
			Kids and families<br/>
			Building career skills<br/>
			Cultivating mind and spirit<br/>
			Learning outdoors<br/>
			Earning certificates or Radians<br/>
			Helping the community<br/>
			Helping a non-profit<br/>
			Increasing self-reliance<br/>
		</div>
		<div id="digital-commons" class="rounded-box">
			<h3>Digital Commons</h3>
			Videos, Documents, Blogs, and Podcasts generated by Local Learning
			<br/>
			<br/>
			Learning Commons Youtube Channel
			<br/>
		</div>
		<div id="feed">
			<h3>The Ubiquitous Stream</h3>
		</div>
		</div>
	</div>
	</div>

</div>
{% endblock %}

learningcommons/templates/login.html
{% extends 'base.html' %}
{% block title %}List Your Workshop, Discussion Group, or Class | Piedmont Learning Commons{% endblock %}
{% block content %}	
	<div id="main-fullwidth">		
	{% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
    	{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
    </div>
{% endblock %}

learningcommons/templates/submitlearning.html
{% extends 'base.html' %}
{% block title %}List Your Workshop, Discussion Group, or Class | Piedmont Learning Commons{% endblock %}
{% block content %}	
	<div id="main-fullwidth" class="rounded-box">
	{% if user.is_authenticated %}
		{% if form.errors %}
	        <p style="color: red;">
	            Please correct the error{{ form.errors|pluralize }} below.
	        </p>
	    {% endif %}
	    <form action="" method="post">
	    	{% csrf_token %}
	        <table>
	            {{ form.as_table }}
	        </table>
	        <input type="submit" value="Submit">
	    </form>
	{% else %}
		{{ errors }}
		Log in to submit a class or <a href="/register">Register</a> for a new account.
		<form action="" method="post">
			{% csrf_token %}
			<table>
				{{ loginform.as_table }}
			</table>
			<input type="submit" value="Submit">
			
		</form>
	{% endif %}
    </div>
{% endblock %}

learningcommons/templates/view-all.html
{% extends 'base.html' %}

{% block title %}View All Local Classes | PLC{% endblock %}

{% block content %}
<div id="main-fullwidth" class="rounded-box">
			<div class="class-listing">
				<strong>
				<div class="class-name">
					Learning Name
				</div>
				<div class="class-subject">
					Subject
				</div>
				<div class="class-format">
					Type
				</div>
				<div class="class-nextdate">
					Date
				</div>
				<div class="class-isfree">
					Free?
				</div>
				</strong>
			</div> </strong>
			{% for class in classes %}
			<div class="class-listing">
				<div class="class-name">
					<a href='../viewlearning/{{ class.classurl }}'>{{ class }}</a>
				</div>
				<div class="class-subject">
					{{ class.classsubject }}
				</div>
				<div class="class-format">
					{{ class.get_classformat_display }}
				</div>
				<div class="class-nextdate">
					{{ class.classnextdate|date:"M d" }}
				</div>
				<div class="class-isfree">
					{{ class.classisfree }}
				</div>
			</div>
			<br/>
			{% endfor %}
{% endblock %}
</div>

learningcommons/templates/viewlearning.html
{% extends 'base.html' %}

{% block title %}Learn About {{ class.classtitle }} {% if class.classtown %}in {{ class.classtown }}{% endif %} | PLC{% endblock %}

{% block content %}
<div id="content">
	<div class="grid">
<div class="col-2-3">
	<div class="rounded-box">
<h2>{{ class.classtitle }}</h2>
<p>{{ class.classdescription }}</p>
<p>Created by <a href='../viewuserprofile/{{ class.classcreator }}'>{{ class.classcreator }}</a></p>
</div>
</div>
<div class="col-1-3">
	<div class="rounded-box">
<h2>Join This Learning</h2>
<p>Here's how to be a part of this Learning:</p>
<p>{{ class.classlocation }}</p>
<p> 
<em>Information provided by Learning creator. Contact them with any questions.</em></p>
</div>
</div>
{% endblock %}
</div>
</div>